let Cvs = {
    SET_BASICS_INFORMATIONS:"SET_BASICS_INFORMATIONS",
    SET_EDUCATIONS:"SET_EDUCATIONS",
    SET_EDUCATIONS_LIST:"SET_EDUCATIONS_LIST",
    SET_SKILLS:"SET_SKILLS",
    SET_SUMMARY:"SET_SUMMARY",
    SET_CERTIFICATIONS:"SET_CERTIFICATIONS",
    SET_WORK_EXPERIENCE:"SET_WORK_EXPERIENCE"
}

export default Cvs;